FROM node:12.18.1-slim

COPY ./practica_creativa2/bookinfo/src/ratings/* /opt/microservices/

ENV SERVICE_VERSION=v1

WORKDIR /opt/microservices

RUN npm install

EXPOSE 9080

CMD ["node", "ratings.js", "9080"]
